### ISSUE TITLE
GitLab API v4 Support?

### ISSUE THREAD

**Issue by strausmann** [terramar-labs/packages#97]
Hello,

is the GitLab API v4 now supported ?

https://about.gitlab.com/2018/06/01/api-v3-removal-impending/

Thanks

Regards,

Bjoern

**Comment by tyler-sommer** [comment]
Thanks for this note. I've just merged #63 into master.

If you could, please try out the latest master and let me know if you run into any issues. I will try to find some time to do more testing myself, as well. Cheers!

**Comment by robertpustulka** [comment]
HI @tyler-sommer 

I checked out the fresh master branch, run composer install and still getting:
`Skipping Exception 'The "https://gitlab.com/api/v3/projects/..." file could not be downloaded (HTTP/1.1 410 Gone)'.`

**Comment by robertpustulka** [comment]
@tyler-sommer 

Is there a reason `composer/composer` is locked at `1.4.3` and libs are replaced by [this](https://github.com/terramar-labs/packages/tree/master/lib/Composer/Repository/Vcs)?

**Comment by robertpustulka** [comment]
I tried to update the composer to the latest version and replace `v3` to `v4` here: https://github.com/terramar-labs/packages/blob/master/lib/Composer/Repository/Vcs/GitLabDriver.php#L244

I'm getting `Skipping Exception 'Undefined index: public'.` now.

**Comment by tyler-sommer** [comment]
@robertpustulka Check these [notes](https://github.com/terramar-labs/packages/blob/master/lib/Composer/NOTES.md) for an explanation there. Nice catch, though, that definitely needs to be addressed. Unfortunately, I don't have the bandwidth to get this corrected right now.

The error you're seeing looks to be due to the "public" field in the JSON received not being there in the v4 API https://github.com/terramar-labs/packages/blob/master/lib/Composer/Repository/Vcs/GitLabDriver.php#L296

It would be best to remove the monkey patch altogether, but if thats not possible just updating Composer and then update the monkey patched files, ensuring that these [3 lines to the github driver](https://github.com/terramar-labs/packages/blob/3a5d50d1f3f26eab3038f65d97fb44daeeb1f781/lib/Composer/Repository/Vcs/GitHubDriver.php#L332-334) and these [3 lines to the gitlab driver](https://github.com/terramar-labs/packages/blob/3a5d50d1f3f26eab3038f65d97fb44daeeb1f781/lib/Composer/Repository/Vcs/GitLabDriver.php#L354-L356) still exist afterward.

**Comment by tyler-sommer** [comment]
Quick update for those interested, #98 should fix the GitLabDriver.php issues. Please give it a shot and let me know if you run into any further problems. Thanks again!

**Comment by wwulfric** [comment]
Hi, my gitlab's version is 7.X and only supports v3 api. Which packages version support gitlab v3 api? I use the latest version and cannot work

**Comment by tyler-sommer** [comment]
[Version 3.2](https://github.com/terramar-labs/packages/releases/tag/3.2.0) should work for you, @wwulfric. Cheers

**Comment by webmaster777** [comment]
There's an undefined function call in the synchronizePackages method. I'll submit a PR asap

**Comment by tyler-sommer** [comment]
This seems to be resolved. If you run into further issues related to this change, please open a new issue. Thanks!
